### ISSUE TITLE
Setup simple command line & git reference for beginners

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe#16]
**Description**
Setup simple command line & git reference for beginners. Such as designers, marketers, etc.

**Documentation tasks**
- [x] Terms & Terminology
- [x] Bash or Terminal Shell Commands
- [x] Developer Tools and Developer Environment Setup
- [x] Workflow
- [x] How to commit code changes
- [x] Terminal Shell Environment Setup

**Comment by guylepage3** [comment]
https://docs.google.com/document/d/1GggcBX2ilB93-jxKItJf0qsM-WYIZMzDMyHiGjvjs6w/edit#

**Comment by guylepage3** [comment]
Would love to get some comments on this document. cc @faddat @dantrevino @modkaffes Thanks.

**Comment by guylepage3** [comment]
Would love to get some comments on this document. cc @faddat @dantrevino @modkaffes Thanks.

**Comment by modkaffes** [comment]
Hey @guylepage3. Great list! Wish I also had such a list when I was starting out as a dev, instead of having to search everything by hand 😀

I have a few minor observations regarding the linked pdf (I don’t have access to the google doc):

- In section 3.0, items 3. a., b. you probably wanted to say `on master branch` and `develop branch` instead of `master the branch` and `develop the branch` respectively.
- In section 3.0, item 3. f. shouldn’t we add remote branch tracking or does git flow take care of that for us?
- In section 3.0 item 6. feels like there’s something missing 🙂

- In section 3.1 in the `They will appear Green in color if staged correctly. If there are any red after this step, please message me` bit, maybe `green` and `red` should be of same capitalization (ocd, I know) and the `please message me` could be confusing if the newcomer didn’t receive the pdf from you.

- In section 4.0 we could go into more detail of adding aliases to the `~/.bashrc` file for persistence.

**Comment by modkaffes** [comment]
@guylepage3, yep, I’m in. Thanks!

**Comment by guylepage3** [comment]
Done
